# 固定版本标识，照着写就行
version: '3.8'

# 定义要运行的服务
services:
  # 服务名字：web，随便取名
  web:
    # 在当前目录，读取 Dockerfile 自动构建镜像
    build: .
    # 端口映射：宿主机8080 映射 容器内80
    ports:
      - "8080:80"
    # 容器挂了/服务器重启，自动重启容器
    restart: always
